apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-svykomri
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-svykomri:1422c1eb8584994f01a9f99cbb166837ce3d4ac0@sha256:632cbe2e10465b6c83ecd81873b84e1053910416a531329a80686beca2046cce
        name: container-image  
